version: '3.8'

services:
  django:
    image: ghcr.io/pearlpandz/creavo/django
    build: ./
    command: /app/entrypoint.sh
    volumes:
      - ./creavo_admin:/app/creavo_admin
    ports:
      - "8000:8000"