# Generated by Django 5.2 on 2025-10-07 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('short_description', models.TextField(blank=True, default=None, null=True)),
                ('bg_color', models.TextField(blank=True, default=None, null=True)),
                ('order', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(default=None, upload_to='media/')),
                ('image', models.URLField(blank=True, null=True)),
                ('media_type', models.CharField(choices=[('image', 'Image (png, jpg, webp, gif)'), ('video', 'Video')], default=None, max_length=50)),
                ('event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.event')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(default=None, upload_to='')),
                ('image', models.URLField(null=True)),
                ('thumbnail', models.URLField(null=True)),
                ('media_type', models.CharField(choices=[('image', 'Image (png, jpg, webp, gif)'), ('video', 'Video')], default=None, max_length=50)),
                ('title', models.CharField(max_length=100, null=True)),
                ('short_description', models.TextField(blank=True, default=None, null=True)),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=5, max_length=10)),
                ('categories', models.ManyToManyField(blank=True, related_name='media', to='api.category')),
                ('subcategories', models.ManyToManyField(blank=True, related_name='media', to='api.subcategory')),
            ],
        ),
    ]
