# Generated by Django 4.2.13 on 2025-12-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='subcategories',
        ),
        migrations.AddField(
            model_name='media',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='media', to='api.subcategory'),
        ),
    ]
