# Generated by Django 5.2 on 2025-07-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_media_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=5, max_length=10),
        ),
    ]
