# Generated by Django 5.2 on 2025-10-10 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_media_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image (png, jpg, webp, gif)'), ('video', 'Video')], default='image', max_length=50),
        ),
        migrations.RemoveField(
            model_name='media',
            name='subcategories',
        ),
        migrations.AddField(
            model_name='media',
            name='subcategories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='api.subcategory'),
        ),
    ]
