# Generated by Django 5.2 on 2025-10-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_is_active_subcategory_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image (png, jpg, webp, gif)'), ('video', 'Video (mp4, mov, avi, mkv)')], default='image', max_length=50),
        ),
    ]
