# Generated by Django 5.2 on 2025-11-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coupon_code',
            field=models.CharField(blank=True, help_text='Applied coupon code (if any)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='free_subscription_days',
            field=models.PositiveIntegerField(default=0, help_text='Number of additional free subscription days for this user'),
        ),
    ]
