# Generated by Django 5.2 on 2025-07-19 06:16

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('api', '0003_media_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='business_cat_count',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='enabled_ratings',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='general_cat_count',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='language_cat_count',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='show_trending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='business_category',
            field=models.ManyToManyField(related_name='business_category', to='api.subcategory'),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.ManyToManyField(related_name='languages', to='api.subcategory'),
        ),
    ]
