# Generated by Django 5.2 on 2025-07-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subscription_business_cat_count_and_more'),
        ('api', '0003_media_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='business_category',
            field=models.ManyToManyField(blank=True, related_name='business_category', to='api.subcategory'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.ManyToManyField(blank=True, related_name='languages', to='api.subcategory'),
        ),
    ]
