# Generated by Django 5.2 on 2025-07-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_business_category_alter_user_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='masterdistributor',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
