# Generated by Django 5.2 on 2025-08-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_distributor_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='daily_download_limit',
            field=models.DecimalField(decimal_places=0, default=3, max_digits=10),
        ),
    ]
