# Generated by Django 5.2 on 2025-07-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('media', models.FileField(default=None, upload_to='')),
                ('image', models.URLField(null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('order', models.IntegerField(default=1)),
            ],
        ),
    ]
