# Generated by Django 4.2.13 on 2025-12-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('media', models.FileField(default=None, upload_to='')),
                ('image', models.URLField(null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('order', models.IntegerField(default=1)),
                ('subcategories', models.ManyToManyField(blank=True, related_name='frame_types', to='api.subcategory')),
            ],
        ),
    ]
