# Generated by Django 5.2 on 2025-10-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_media_media_type'),
        ('frames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frametype',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='frame_types', to='api.subcategory'),
        ),
    ]
